export const GET_CARDS_PENDING = "GET_CARDS_PENDING";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";
export const GET_CARDS_FAILURE = "GET_CARDS_FAILURE";

export const CREATE_CARD_PENDING = "CREATE_CARD_PENDING";
export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS";
export const CREATE_CARD_FAILURE = "CREATE_CARD_FAILURE";

export const SHARE_CARD_PENDING = "SHARE_CARD_PENDING";
export const SHARE_CARD_SUCCESS = "SHARE_CARD_SUCCESS";
export const SHARE_CARD_FAILURE = "SHARE_CARD_FAILURE";
export const CLEAR_SHARE_LINK = "CLEAR_SHARE_LINK";

export const DUPLICATE_CARD_PENDING = "DUPLICATE_CARD_PENDING";
export const DUPLICATE_CARD_SUCCESS = "DUPLICATE_CARD_SUCCESS";
export const DUPLICATE_CARD_FAILURE = "DUPLICATE_CARD_FAILURE";

export const DELETE_CARD_PENDING = "DELETE_CARD_PENDING";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const DELETE_CARD_FAILURE = "DELETE_CARD_FAILURE";