const Color = {
    maize: '#f3c442',
    orangish: '#fa7745',
    greenTeal: '#11b777',
    background: '#f8f6f6',
    textColor: '#434343',
};

// (some color names were already on Zeplin or autogenerated by it when I was trying to export them)

export default Color;